/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.orphanage.view;

import com.controller.SearchingAlgorithm.BinarySearch;
import com.orphanage.controller.datastructure.algorithm.SelectionSort;
import com.orphanage.model.OrphanModel;
import com.orphanage.util.ValidationUtil;
import static com.orphanage.util.ValidationUtil.isValidCredentials;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JLabel;

import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author victus
 */
public class OrphanageApp extends javax.swing.JFrame {

    private static short id = 4;
    private HashMap<Integer, OrphanModel> orphanList = new HashMap<>();
    private java.awt.CardLayout cardLayout;

    /**
     * Creates new form OrpanageApp
     */
    public OrphanageApp() {
        OrphanModel orphan1 = new OrphanModel((short) 1, "DanDan", "m", (short) 3, (short) 4, (short) 5, "Female", "B-");
        OrphanModel orphan2 = new OrphanModel((short) 2, "Rambsqv", "m", (short) 4, (short) 4, (short) 5, "Female", "B+");
        OrphanModel orphan3 = new OrphanModel((short) 3, "Bampo", "m", (short) 5, (short) 4, (short) 5, "Female", "B-");
        OrphanModel orphan4 = new OrphanModel((short) 4, "Son", "m", (short) 6, (short) 4, (short) 5, "Female", "B-");

        orphanList.put((int) orphan1.getOrphanID(), orphan1);
        orphanList.put((int) orphan2.getOrphanID(), orphan2);
        orphanList.put((int) orphan3.getOrphanID(), orphan3);
        orphanList.put((int) orphan4.getOrphanID(), orphan4);

        initComponents();
        initializeLayout();
        startProgress();
        setTableHeaderFont(orphanageTb);
        setTableHeaderListener();
        refreshTable();

    }

    private void setTableHeaderFont(javax.swing.JTable table) {
        javax.swing.table.JTableHeader header = table.getTableHeader();
        header.setFont(new Font("Times New Roman", Font.PLAIN, 14));
    }

    public String getTfText(javax.swing.JTextField jTextField) {
        return jTextField.getText();
    }

    public void setTfText(javax.swing.JTextField jTextField, String text) {
        jTextField.setText(text);
    }

    public void clearText(javax.swing.JTextField jTextField) {
        jTextField.setText("");
    }

    private void setTableHeaderListener() {
        orphanageTb.getTableHeader().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int column = orphanageTb.columnAtPoint(e.getPoint());
                sort(column);

            }
        });
    }

    public void sort(int column) {
        ArrayList<OrphanModel> list = new ArrayList<>(orphanList.values());
        switch (column) {
            case 0:
                refreshTable(SelectionSort.sortById(list, true));
                break;
            case 1:
                refreshTable(SelectionSort.sortByFirstName(list, true));
                break;
            case 2:
                refreshTable(SelectionSort.sortByFirstName(list, true));
                break;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPnl = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        homePagePnl = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        managePnl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orphanageTb = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        idTf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ageTf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        weightTf = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lastNameTf = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        heightTf = new javax.swing.JTextField();
        bloodGroupCb = new javax.swing.JComboBox<>();
        genderCb = new javax.swing.JComboBox<>();
        deleteBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        firstNameTf = new javax.swing.JTextField();
        searchBarCb = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        searchKeyTf = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        addPnl = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        newFirstNameTf = new javax.swing.JTextField();
        newLastNameTf = new javax.swing.JTextField();
        newAgeTf = new javax.swing.JTextField();
        newHeightTf = new javax.swing.JTextField();
        newWeightTf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        newGenderCb = new javax.swing.JComboBox<>();
        newBloodGroupCb = new javax.swing.JComboBox<>();
        addFirstNameErrLbl = new javax.swing.JLabel();
        addGenderErrLbl = new javax.swing.JLabel();
        addBloodGroupErrLbl = new javax.swing.JLabel();
        addLastNameErrLbl = new javax.swing.JLabel();
        addAgeErrLbl = new javax.swing.JLabel();
        addWeightErrLbl = new javax.swing.JLabel();
        addHeightErrLbl = new javax.swing.JLabel();
        aboutUsPnl = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        loginPnl = new javax.swing.JPanel();
        usernameTf = new javax.swing.JTextField();
        passwordTf = new javax.swing.JPasswordField();
        userIconLabel = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lockIconLabel = new javax.swing.JLabel();
        BackgroundImage = new javax.swing.JLabel();
        loginSideImageLabel = new javax.swing.JLabel();
        loadingPnl = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();

        mainPnl.setLayout(new java.awt.BorderLayout());

        jTabbedPane2.setBackground(new java.awt.Color(56, 111, 164));
        jTabbedPane2.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane2.setFont(new java.awt.Font("HP Simplified Hans", 0, 18)); // NOI18N
        jTabbedPane2.setOpaque(true);

        homePagePnl.setBackground(new java.awt.Color(218, 223, 234));
        homePagePnl.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel2.setText("Welcome To Orphanage Management System");
        homePagePnl.add(jLabel2);
        jLabel2.setBounds(260, 70, 829, 90);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
        );

        homePagePnl.add(jPanel1);
        jPanel1.setBounds(70, 480, 380, 290);

        jPanel2.setBackground(new java.awt.Color(153, 0, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
        );

        homePagePnl.add(jPanel2);
        jPanel2.setBounds(490, 480, 400, 290);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
        );

        homePagePnl.add(jPanel3);
        jPanel3.setBounds(940, 480, 390, 290);

        jLabel11.setFont(new java.awt.Font("Pristina", 0, 24)); // NOI18N
        jLabel11.setText("For God and For all");
        homePagePnl.add(jLabel11);
        jLabel11.setBounds(910, 150, 200, 29);

        jTabbedPane2.addTab("Home Page", homePagePnl);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("HP Simplified Hans", 0, 18)); // NOI18N
        jTabbedPane1.setOpaque(true);

        managePnl.setBackground(new java.awt.Color(236, 239, 239));

        orphanageTb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        orphanageTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FIrst Name", "Last Name", "Age", "Weight(Kg)", "Height(cm)", "Gender", "BloodGroup"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orphanageTb.setToolTipText("");
        orphanageTb.setGridColor(new java.awt.Color(255, 255, 255));
        orphanageTb.getTableHeader().setReorderingAllowed(false);
        orphanageTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orphanageTbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(orphanageTb);
        if (orphanageTb.getColumnModel().getColumnCount() > 0) {
            orphanageTb.getColumnModel().getColumn(0).setResizable(false);
            orphanageTb.getColumnModel().getColumn(1).setResizable(false);
            orphanageTb.getColumnModel().getColumn(2).setResizable(false);
            orphanageTb.getColumnModel().getColumn(3).setResizable(false);
            orphanageTb.getColumnModel().getColumn(4).setResizable(false);
            orphanageTb.getColumnModel().getColumn(5).setResizable(false);
            orphanageTb.getColumnModel().getColumn(6).setResizable(false);
            orphanageTb.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new Color(0,0,0,(int)0.01), 3, true));

        idTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        idTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("ID");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Last Name");

        ageTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ageTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("First Name");

        weightTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        weightTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("Age");

        lastNameTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lastNameTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("Weight");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("Height");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setText("Gender");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setText("Blood Group");

        heightTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        heightTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bloodGroupCb.setBackground(new Color(0,0,0,(int)0.01));
        bloodGroupCb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bloodGroupCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        bloodGroupCb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        genderCb.setBackground(new Color(0,0,0,(int)0.01));
        genderCb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        genderCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        genderCb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        firstNameTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        firstNameTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17)
                    .addComponent(jLabel15))
                .addGap(63, 63, 63)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weightTf, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lastNameTf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                        .addComponent(idTf, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ageTf, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(firstNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bloodGroupCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(deleteBtn)
                        .addGap(18, 18, 18)
                        .addComponent(updateBtn))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genderCb, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(heightTf, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idTf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(heightTf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel18)
                            .addComponent(genderCb, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel19)
                            .addComponent(bloodGroupCb, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lastNameTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteBtn)
                            .addComponent(updateBtn)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(ageTf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(weightTf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel15)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel17)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        searchBarCb.setBackground(new Color(0,0,0,(int)0.01));
        searchBarCb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        searchBarCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "First Name", "Last Name", "Age", "Weight", "Height", "Gender", "Blood Group" }));
        searchBarCb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel25.setText("Search By:");

        searchKeyTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        searchKeyTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        searchBtn.setText("Search Button");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout managePnlLayout = new javax.swing.GroupLayout(managePnl);
        managePnl.setLayout(managePnlLayout);
        managePnlLayout.setHorizontalGroup(
            managePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managePnlLayout.createSequentialGroup()
                .addGroup(managePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(managePnlLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(managePnlLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(managePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(managePnlLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(managePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(managePnlLayout.createSequentialGroup()
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(searchBarCb, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(searchKeyTf, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(managePnlLayout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(searchBtn)))))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        managePnlLayout.setVerticalGroup(
            managePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managePnlLayout.createSequentialGroup()
                .addGroup(managePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(managePnlLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(managePnlLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(managePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchBarCb, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchKeyTf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(searchBtn)))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage", managePnl);

        addPnl.setBackground(new java.awt.Color(236, 239, 239));

        addBtn.setText("Add Child");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("First Name");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Last Name");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Weight");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Height");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Gender");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Blood Group");

        newFirstNameTf.setBackground(new Color(0,0,0,(int) 0.01*255));
        newFirstNameTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        newFirstNameTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        newLastNameTf.setBackground(new Color(0,0,0,(int) 0.01*255));
        newLastNameTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        newLastNameTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        newAgeTf.setBackground(new Color(0,0,0,(int) 0.01*255));
        newAgeTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        newAgeTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        newHeightTf.setBackground(new Color(0,0,0,(int) 0.01*255));
        newHeightTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        newHeightTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        newWeightTf.setBackground(new Color(0,0,0,(int) 0.01*255));
        newWeightTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        newWeightTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Age");

        newGenderCb.setBackground(new Color(0,0,0,(int)0.01));
        newGenderCb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        newGenderCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        newGenderCb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        newBloodGroupCb.setBackground(new Color(0,0,0,(int)0.01));
        newBloodGroupCb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        newBloodGroupCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        newBloodGroupCb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        addFirstNameErrLbl.setText("jLabel26");

        addGenderErrLbl.setText("jLabel27");

        addBloodGroupErrLbl.setText("jLabel27");

        addLastNameErrLbl.setText("jLabel26");

        addAgeErrLbl.setText("jLabel26");

        addWeightErrLbl.setText("jLabel26");

        addHeightErrLbl.setText("jLabel26");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newHeightTf, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newGenderCb, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addGenderErrLbl)
                            .addComponent(newWeightTf, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addWeightErrLbl)
                            .addComponent(addHeightErrLbl)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addBloodGroupErrLbl)
                                    .addComponent(newBloodGroupCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addLastNameErrLbl)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(addFirstNameErrLbl))
                                        .addComponent(newFirstNameTf, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                                        .addComponent(newLastNameTf)
                                        .addComponent(newAgeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(addAgeErrLbl))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(newFirstNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addFirstNameErrLbl)
                .addGap(8, 8, 8)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newLastNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addLastNameErrLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newAgeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addAgeErrLbl)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newWeightTf, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addWeightErrLbl)
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newHeightTf, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addHeightErrLbl)
                .addGap(11, 11, 11)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newGenderCb, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(4, 4, 4)
                .addComponent(addGenderErrLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBloodGroupCb, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addBloodGroupErrLbl)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout addPnlLayout = new javax.swing.GroupLayout(addPnl);
        addPnl.setLayout(addPnlLayout);
        addPnlLayout.setHorizontalGroup(
            addPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPnlLayout.createSequentialGroup()
                .addGroup(addPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPnlLayout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(addBtn))
                    .addGroup(addPnlLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(684, Short.MAX_VALUE))
        );
        addPnlLayout.setVerticalGroup(
            addPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPnlLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(addBtn)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add ", addPnl);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane2.addTab("Orphanage List", jPanel5);

        aboutUsPnl.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel20.setText("About Us");
        jLabel20.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel21.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(56, 111, 164));
        jLabel21.setText(" who have lost their home, offering a haven where children can find a family, even when they have none.");

        jLabel22.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(56, 111, 164));
        jLabel22.setText("An orphanage is a place where love is given to those");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel23.setText("Who We Are");
        jLabel23.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout aboutUsPnlLayout = new javax.swing.GroupLayout(aboutUsPnl);
        aboutUsPnl.setLayout(aboutUsPnlLayout);
        aboutUsPnlLayout.setHorizontalGroup(
            aboutUsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutUsPnlLayout.createSequentialGroup()
                .addGap(565, 565, 565)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(aboutUsPnlLayout.createSequentialGroup()
                .addGroup(aboutUsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutUsPnlLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addGroup(aboutUsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutUsPnlLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(208, 208, 208))
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(aboutUsPnlLayout.createSequentialGroup()
                        .addGap(574, 574, 574)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        aboutUsPnlLayout.setVerticalGroup(
            aboutUsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutUsPnlLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addGap(26, 26, 26)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(560, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("About us", aboutUsPnl);

        mainPnl.add(jTabbedPane2, java.awt.BorderLayout.CENTER);

        loginPnl.setMaximumSize(new java.awt.Dimension(640, 471));
        loginPnl.setMinimumSize(new java.awt.Dimension(640, 471));
        loginPnl.setPreferredSize(new java.awt.Dimension(640, 471));
        loginPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameTf.setBackground(new Color(0,0,0,(int)0.01));
        usernameTf.setForeground(new java.awt.Color(255, 255, 255));
        usernameTf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameTf.setText("Username");
        usernameTf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        usernameTf.setCaretColor(new java.awt.Color(255, 255, 255));
        usernameTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameTfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameTfFocusLost(evt);
            }
        });
        loginPnl.add(usernameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 200, 50));

        passwordTf.setBackground(new Color(0,0,0,0));
        passwordTf.setForeground(new java.awt.Color(255, 255, 255));
        passwordTf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordTf.setText("Password");
        passwordTf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        passwordTf.setCaretColor(new java.awt.Color(255, 255, 255));
        passwordTf.setEchoChar((char) 0);
        passwordTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordTfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordTfFocusLost(evt);
            }
        });
        loginPnl.add(passwordTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 200, 50));

        userIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/orphanage/resources/user.png"))); // NOI18N
        loginPnl.add(userIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("LOGIN");
        loginBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        loginBtn.setContentAreaFilled(false);
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        loginPnl.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 140, 30));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" System");
        loginPnl.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 80, 40));

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Welcome To Orphanage Management ");
        loginPnl.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 330, 70));

        lockIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/orphanage/resources/lock.png"))); // NOI18N
        loginPnl.add(lockIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/orphanage/resources/background.png"))); // NOI18N
        BackgroundImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        loginPnl.add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 380, 490));

        loginSideImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/orphanage/resources/loginImage.jpg"))); // NOI18N
        loginSideImageLabel.setText("jLabel25");
        loginPnl.add(loginSideImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, -10, 290, 480));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loadingPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        progressBar.setForeground(new Color(0,0,0));
        progressBar.setValue(50);
        progressBar.setBorder(null);
        progressBar.setBorderPainted(false);
        progressBar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        progressBar.setFocusable(false);
        progressBar.setRequestFocusEnabled(false);
        loadingPnl.add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 560, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/orphanage/resources/loadingbg.jpg"))); // NOI18N
        loadingPnl.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(loadingPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(loadingPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTfFocusGained
        if (getTfText(usernameTf).equals("Username")) {
            clearText(usernameTf);
        }
    }//GEN-LAST:event_usernameTfFocusGained

    private void passwordTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTfFocusGained
        if (getTfText(passwordTf).equals("Password")) {
            passwordTf.setEchoChar('*');
            clearText(passwordTf);
        }
    }//GEN-LAST:event_passwordTfFocusGained

    private void usernameTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTfFocusLost
        if (getTfText(usernameTf).equals("")) {
            setTfText(usernameTf, "Username");
        }
    }//GEN-LAST:event_usernameTfFocusLost

    private void passwordTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTfFocusLost
        if (getTfText(passwordTf).equals("")) {
            passwordTf.setEchoChar((char) 0);
            setTfText(passwordTf, "Password");
        }
    }//GEN-LAST:event_passwordTfFocusLost

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        if (isValidCredentials(getTfText(usernameTf), getTfText(passwordTf))) {
            loadScreen("MainScreen");
            setFullScreen();
            setLocationRelativeTo(null);
        } else {
            JOptionPane.showMessageDialog(null, "Username or Password is incorrect", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void orphanageTbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orphanageTbMouseClicked
        int row = orphanageTb.rowAtPoint(evt.getPoint());
        setTfText(idTf, String.valueOf(orphanageTb.getValueAt(row, 0)));
        setTfText(firstNameTf, (String) orphanageTb.getValueAt(row, 1));
        setTfText(lastNameTf, (String) orphanageTb.getValueAt(row, 2));
        setTfText(ageTf, String.valueOf(orphanageTb.getValueAt(row, 3)));
        setTfText(weightTf, String.valueOf(orphanageTb.getValueAt(row, 4)));
        setTfText(heightTf, String.valueOf(orphanageTb.getValueAt(row, 5)));
        genderCb.setSelectedItem(orphanageTb.getValueAt(row, 6));
        bloodGroupCb.setSelectedItem(orphanageTb.getValueAt(row, 7));

    }//GEN-LAST:event_orphanageTbMouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        try {
            boolean isValid = true;
            isValid &= ValidationUtil.isValidId(Short.parseShort(getTfText(newFirstNameTf)));
            isValid &= ValidationUtil.isValidName(getTfText(newFirstNameTf));
            isValid &= ValidationUtil.isValidName(getTfText(newLastNameTf));
            isValid &= ValidationUtil.isValidAge(Short.parseShort(getTfText(newAgeTf)));
            isValid &= ValidationUtil.isValidWeight(Short.parseShort(getTfText(newWeightTf)));
            isValid &= ValidationUtil.isValidHeight(Short.parseShort(getTfText(newHeightTf)));
            isValid &= ValidationUtil.isValidGender(newGenderCb.getSelectedItem().toString());
            if (isValid &= ValidationUtil.isValidBloodGroup(newBloodGroupCb.getSelectedItem().toString())) {
                addGenderErrLbl.setText("Error");
            }
            if (isValid) {
                String firstName = getTfText(newFirstNameTf);
                String lastName = getTfText(newLastNameTf);
                short age = Short.parseShort(getTfText(newAgeTf));
                short weight = Short.parseShort(getTfText(newWeightTf));
                short height = Short.parseShort(getTfText(newHeightTf));
                String gender = (String) newGenderCb.getSelectedItem();
                String bloodGroup = (String) newBloodGroupCb.getSelectedItem();

                OrphanModel newOrphan = new OrphanModel(id, firstName, lastName, age, weight, height, gender, bloodGroup);
                orphanList.put((int) id, newOrphan);
                JOptionPane.showMessageDialog(null, "Orphan has been updated", "update Succesful", JOptionPane.INFORMATION_MESSAGE);
                refreshTable();
            }
        } catch (NumberFormatException E) {
            JOptionPane.showMessageDialog(null, "Invalid Details", "update Unsuccesful", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private boolean validateField(JLabel label, String msg, boolean isValidFormat) {
        if (!isValidFormat) {
            label.setText(msg);
            return false;
        } else {
            label.setText("");
            return true;
        }
    }
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        try {
            boolean isValid = true;
            isValid &= validateField(addFirstNameErrLbl, "First name is invalid", ValidationUtil.isValidName(getTfText(newFirstNameTf)));
            isValid &= validateField(addLastNameErrLbl, "Last name is invalid", ValidationUtil.isValidName(getTfText(newLastNameTf)));
            isValid &= validateField(addAgeErrLbl, "Age is invalid", ValidationUtil.isValidAge(Short.parseShort(getTfText(newAgeTf))));
            isValid &= validateField(addWeightErrLbl, "Weight is invalid", ValidationUtil.isValidWeight(Short.parseShort(getTfText(newWeightTf))));
            isValid &= validateField(addHeightErrLbl, "Height is invalid", ValidationUtil.isValidHeight(Short.parseShort(getTfText(newHeightTf))));
            isValid &= validateField(addGenderErrLbl, "Gender is invalid", ValidationUtil.isValidGender(newGenderCb.getSelectedItem().toString()));
            isValid &= validateField(addBloodGroupErrLbl, "Blood Group is invalid", ValidationUtil.isValidBloodGroup(newBloodGroupCb.getSelectedItem().toString()));


            if (isValid) {
                String firstName = getTfText(newFirstNameTf);
                String lastName = getTfText(newLastNameTf);
                short age = Short.parseShort(getTfText(newAgeTf));
                short weight = Short.parseShort(getTfText(newWeightTf));
                short height = Short.parseShort(getTfText(newHeightTf));
                String gender = newGenderCb.getSelectedItem().toString();
                String bloodGroup = newBloodGroupCb.getSelectedItem().toString();
                OrphanModel newOrphan = new OrphanModel(++id, firstName, lastName, age, weight, height, gender, bloodGroup);
                orphanList.put((int) id, newOrphan);
                JOptionPane.showMessageDialog(null, "Orphan has been added", "Insert Succesful", JOptionPane.INFORMATION_MESSAGE);
                refreshTable();
            }
        } catch (NumberFormatException E) {
            JOptionPane.showMessageDialog(null, "Invalid Details", "Insert Unsuccesful", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed

        try {
            int idToBeDeleted = Integer.parseInt(getTfText(idTf));
            orphanList.remove(idToBeDeleted);
            refreshTable();
            JOptionPane.showMessageDialog(null, "Orphan Detail has been deleletd", "Delete Succesful", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException E) {
            JOptionPane.showMessageDialog(null, "Invalid Details", "Delete Unsuccesful", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed

        String searchBy = (String) searchBarCb.getSelectedItem();
        String target = getTfText(searchKeyTf);
        searchByAttribute(searchBy, target);

    }//GEN-LAST:event_searchBtnActionPerformed

    public void searchByAttribute(String searchBy, String target) {
        ArrayList<OrphanModel> list = new ArrayList<>(orphanList.values());
        if (searchBy.equals("Id")) {
            try {

                refreshTable(BinarySearch.binarySearchbyId(list, 0, list.size() - 1, Integer.parseInt(target)));
            } catch (NumberFormatException e) {

            }
        } else if (searchBy.equals("First Name")) {
            try {
                refreshTable(BinarySearch.binarySearchbyFirstName(list, 0, list.size() - 1, target));
            } catch (NumberFormatException e) {

            }

        } else if (searchBy.equals("Last Name")) {
            try {
                refreshTable(BinarySearch.binarySearchbyLastName(list, 0, list.size() - 1, target));
            } catch (NumberFormatException e) {
                // Handle error
            }
        } else if (searchBy.equals("Age")) {
            try {
                refreshTable(BinarySearch.binarySearchbyAge(list, 0, list.size() - 1, Short.parseShort(target)));
            } catch (NumberFormatException e) {
                // Handle error
            }
        } else if (searchBy.equals("Weight")) {
            try {
                refreshTable(BinarySearch.binarySearchbyWeight(list, 0, list.size() - 1, Short.parseShort(target)));
            } catch (NumberFormatException e) {
                // Handle error
            }
        } else if (searchBy.equals("Height")) {
            try {
                refreshTable(BinarySearch.binarySearchbyHeight(list, 0, list.size() - 1, Short.parseShort(target)));
            } catch (NumberFormatException e) {
                // Handle error
            }
        } else if (searchBy.equals("Gender")) {
            try {
                refreshTable(BinarySearch.binarySearchbyGender(list, 0, list.size() - 1, target));
            } catch (NumberFormatException e) {
                // Handle error
            }
        } else if (searchBy.equals("Blood Group")) {
            try {
                refreshTable(BinarySearch.binarySearchbyBloodGroup(list, 0, list.size() - 1, target));
            } catch (NumberFormatException e) {
                // Handle error
            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrphanageApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrphanageApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrphanageApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrphanageApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        OrphanageApp app = new OrphanageApp();
        //</editor-fold>

        /* Create and display the form */
 /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            app.setVisible(true);
        });

        app.startProgress();
    }

    private void setFullScreen() {
        // Maximize the frame 
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    private void initializeLayout() {
        cardLayout = new java.awt.CardLayout();
        getContentPane().setLayout(cardLayout);

        // Add panels with unique identifiers
        getContentPane().add(loadingPnl, "LoadingScreen");
        getContentPane().add(loginPnl, "LoginScreen");
        getContentPane().add(mainPnl, "MainScreen");

        // Start with the loading screen
        loadScreen("LoadingScreen");
    }

    private void loadScreen(String screenName) {
        cardLayout.show(getContentPane(), screenName);
    }

    private void startProgress() {
        javax.swing.SwingWorker<Void, Integer> worker = new javax.swing.SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {
                for (int i = 0; i <= 100; i++) {
                    Thread.sleep(30); // Simulated delay for progress bar
                    publish(i); // Publish progress
                }
                return null;
            }

            @Override
            protected void process(java.util.List<Integer> chunks) {
                int progress = chunks.get(chunks.size() - 1);
                progressBar.setValue(progress);
            }

            @Override
            protected void done() {
                loadScreen("LoginScreen"); // Switch to login screen

            }
        };
        worker.execute(); // Start the worker thread
    }

    private void refreshTable() {
        DefaultTableModel table = (DefaultTableModel) orphanageTb.getModel();

        // Clear existing rows if needed
        table.setRowCount(0);

        // Populate the table with student data
        this.orphanList.forEach((id, orphan) -> table.addRow(new Object[]{
            orphan.getOrphanID(),
            orphan.getFirstName(),
            orphan.getLastName(),
            orphan.getAge(),
            orphan.getWeight(),
            orphan.getHeight(),
            orphan.getGender(),
            orphan.getBloodGroup()
        }));

    }

    private void refreshTable(ArrayList<OrphanModel> list) {
        DefaultTableModel table = (DefaultTableModel) orphanageTb.getModel();

        // Clear existing rows if needed
        table.setRowCount(0);

        list.forEach(orphan -> table.addRow(new Object[]{
            orphan.getOrphanID(),
            orphan.getFirstName(),
            orphan.getLastName(),
            orphan.getAge(),
            orphan.getWeight(),
            orphan.getHeight(),
            orphan.getGender(),
            orphan.getBloodGroup()
        }));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JPanel aboutUsPnl;
    private javax.swing.JLabel addAgeErrLbl;
    private javax.swing.JLabel addBloodGroupErrLbl;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel addFirstNameErrLbl;
    private javax.swing.JLabel addGenderErrLbl;
    private javax.swing.JLabel addHeightErrLbl;
    private javax.swing.JLabel addLastNameErrLbl;
    private javax.swing.JPanel addPnl;
    private javax.swing.JLabel addWeightErrLbl;
    private javax.swing.JTextField ageTf;
    private javax.swing.JComboBox<String> bloodGroupCb;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField firstNameTf;
    private javax.swing.JComboBox<String> genderCb;
    private javax.swing.JTextField heightTf;
    private javax.swing.JPanel homePagePnl;
    private javax.swing.JTextField idTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField lastNameTf;
    private javax.swing.JPanel loadingPnl;
    private javax.swing.JLabel lockIconLabel;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel loginPnl;
    private javax.swing.JLabel loginSideImageLabel;
    private javax.swing.JPanel mainPnl;
    private javax.swing.JPanel managePnl;
    private javax.swing.JTextField newAgeTf;
    private javax.swing.JComboBox<String> newBloodGroupCb;
    private javax.swing.JTextField newFirstNameTf;
    private javax.swing.JComboBox<String> newGenderCb;
    private javax.swing.JTextField newHeightTf;
    private javax.swing.JTextField newLastNameTf;
    private javax.swing.JTextField newWeightTf;
    private javax.swing.JTable orphanageTb;
    private javax.swing.JPasswordField passwordTf;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JComboBox<String> searchBarCb;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchKeyTf;
    private javax.swing.JButton updateBtn;
    private javax.swing.JLabel userIconLabel;
    private javax.swing.JTextField usernameTf;
    private javax.swing.JTextField weightTf;
    // End of variables declaration//GEN-END:variables

}
