/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.orphanage.view;

import com.orphanage.controller.searchingalgorithm.BinarySearch;
import com.orphanage.controller.datastructure.algorithm.InsertionSort;
import com.orphanage.controller.datastructure.algorithm.MergeSort;
import com.orphanage.controller.datastructure.algorithm.SelectionSort;
import com.orphanage.model.OrphanModel;
import com.orphanage.util.ValidationUtil;
import static com.orphanage.util.ValidationUtil.isValidCredentials;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.NoSuchElementException;
import javax.swing.JLabel;

import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shirish Govind Shrestha LMU ID:23057125
 */
public class OrphanageApp extends javax.swing.JFrame {

    private static short id = 4;
    private HashMap<Integer, OrphanModel> orphanList = new HashMap<>();
    private java.awt.CardLayout cardLayout;

    /**
     * Creates new form OrpanageApp
     */
    public OrphanageApp() {
        OrphanModel orphan1 = new OrphanModel((short) 1, "DanDan", "Ban", (short) 15, (short) 40, (short) 160, "Female", "B-");
        OrphanModel orphan2 = new OrphanModel((short) 2, "Rambsqv", "Sang", (short) 20, (short) 49, (short) 175, "Male", "B+");
        OrphanModel orphan3 = new OrphanModel((short) 3, "Bampo", "Oppo", (short) 12, (short) 54, (short) 145, "Female", "AB-");
        OrphanModel orphan4 = new OrphanModel((short) 4, "Son", "Goku", (short) 5, (short) 20, (short) 109, "Male", "O-");
        OrphanModel orphan5 = new OrphanModel((short) 5, "Don", "Goku", (short) 5, (short) 23, (short) 110, "Male", "O-");
        orphanList.put((int) orphan1.getOrphanID(), orphan1);
        orphanList.put((int) orphan2.getOrphanID(), orphan2);
        orphanList.put((int) orphan3.getOrphanID(), orphan3);
        orphanList.put((int) orphan4.getOrphanID(), orphan4);
        orphanList.put((int) orphan5.getOrphanID(), orphan5);
        initComponents();
        setTableHeaderFont(orphanageTb);
        setTableHeaderListener();
        initializeLayout();
        startProgress();
        refreshTable();

    }

    private void setTableHeaderFont(javax.swing.JTable table) {
        javax.swing.table.JTableHeader header = table.getTableHeader();
        header.setFont(new Font("Times New Roman", Font.PLAIN, 14));
    }

    private String getTfText(javax.swing.JTextField jTextField) {
        return jTextField.getText();
    }

    private void setTfText(javax.swing.JTextField jTextField, String text) {
        jTextField.setText(text);
    }

    private void clearText(javax.swing.JTextField jTextField) {
        jTextField.setText("");
    }

    private void setTableHeaderListener() {
        orphanageTb.getTableHeader().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int column = orphanageTb.columnAtPoint(e.getPoint());
                sort(column);

            }
        });
    }

    private void sort(int column) {
        ArrayList<OrphanModel> list = new ArrayList<>(orphanList.values());
        boolean isDesc = isDescending.isSelected();
        switch (column) {
            case 0 ->
                refreshTable(SelectionSort.sortById(list, isDesc));
            case 1 ->
                refreshTable(MergeSort.mergeSort(list, isDesc, "FirstName"));
            case 2 ->
                refreshTable(InsertionSort.sortByLastName(list, isDesc));
            case 3 ->
                refreshTable(InsertionSort.sortByAge(list, isDesc));
            case 4 ->
                refreshTable(MergeSort.mergeSort(list, isDesc, "Weight"));
            case 5 ->
                refreshTable(MergeSort.mergeSort(list, isDesc, "Height"));
            case 6 ->
                refreshTable(SelectionSort.sortByGender(list, isDesc));
            case 7 ->
                refreshTable(SelectionSort.sortByBloodGroup(list, isDesc));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPnl = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        homePagePnl = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        orphanageListPnl = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        managePnl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orphanageTb = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        idTf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ageTf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        weightTf = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lastNameTf = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        heightTf = new javax.swing.JTextField();
        bloodGroupCb = new javax.swing.JComboBox<>();
        genderCb = new javax.swing.JComboBox<>();
        deleteBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        firstNameTf = new javax.swing.JTextField();
        idErrLbl = new javax.swing.JLabel();
        firstNameErrLbl = new javax.swing.JLabel();
        weightErrLbl = new javax.swing.JLabel();
        ageErrLbl = new javax.swing.JLabel();
        lastNameErrLbl = new javax.swing.JLabel();
        genderErrLbl = new javax.swing.JLabel();
        bloodGroupErrLbl = new javax.swing.JLabel();
        heightErrLbl = new javax.swing.JLabel();
        searchBarCb = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        searchKeyTf = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        isDescending = new javax.swing.JCheckBox();
        addPnl = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        newFirstNameTf = new javax.swing.JTextField();
        newLastNameTf = new javax.swing.JTextField();
        newAgeTf = new javax.swing.JTextField();
        newHeightTf = new javax.swing.JTextField();
        newWeightTf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        newGenderCb = new javax.swing.JComboBox<>();
        newBloodGroupCb = new javax.swing.JComboBox<>();
        addFirstNameErrLbl = new javax.swing.JLabel();
        addGenderErrLbl = new javax.swing.JLabel();
        addBloodGroupErrLbl = new javax.swing.JLabel();
        addLastNameErrLbl = new javax.swing.JLabel();
        addAgeErrLbl = new javax.swing.JLabel();
        addWeightErrLbl = new javax.swing.JLabel();
        addHeightErrLbl = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        aboutUsPnl = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        loginPnl = new javax.swing.JPanel();
        usernameTf = new javax.swing.JTextField();
        passwordTf = new javax.swing.JPasswordField();
        userIconLabel = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lockIconLabel = new javax.swing.JLabel();
        BackgroundImage = new javax.swing.JLabel();
        loginSideImageLabel = new javax.swing.JLabel();
        loadingPnl = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();

        mainPnl.setLayout(new java.awt.BorderLayout());

        jTabbedPane2.setBackground(new java.awt.Color(56, 111, 164));
        jTabbedPane2.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane2.setFont(new java.awt.Font("HP Simplified Hans", 0, 18)); // NOI18N
        jTabbedPane2.setOpaque(true);

        homePagePnl.setBackground(new java.awt.Color(218, 223, 234));
        homePagePnl.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel2.setText("Welcome To Orphanage Management System");
        homePagePnl.add(jLabel2);
        jLabel2.setBounds(260, 70, 829, 90);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel27.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("orphan");

        jLabel29.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Each day 789 ");

        jLabel30.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText(" children become");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        homePagePnl.add(jPanel1);
        jPanel1.setBounds(70, 480, 380, 290);

        jPanel2.setBackground(new java.awt.Color(153, 0, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel28.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Every child needs ");

        jLabel31.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("a Family");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(57, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        homePagePnl.add(jPanel2);
        jPanel2.setBounds(490, 480, 400, 290);

        jPanel3.setBackground(new java.awt.Color(255, 153, 51));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel26.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("a chance to grow and ");

        jLabel32.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Every child deserve ");

        jLabel33.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText(" thrive");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addComponent(jLabel33)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        homePagePnl.add(jPanel3);
        jPanel3.setBounds(940, 480, 390, 290);

        jLabel11.setFont(new java.awt.Font("Pristina", 0, 24)); // NOI18N
        jLabel11.setText("For God and For all");
        homePagePnl.add(jLabel11);
        jLabel11.setBounds(910, 150, 200, 29);

        jTabbedPane2.addTab("Home Page", homePagePnl);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("HP Simplified Hans", 0, 18)); // NOI18N
        jTabbedPane1.setOpaque(true);

        managePnl.setBackground(new java.awt.Color(236, 239, 239));

        orphanageTb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        orphanageTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FIrst Name", "Last Name", "Age", "Weight(Kg)", "Height(cm)", "Gender", "BloodGroup"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orphanageTb.setToolTipText("");
        orphanageTb.setGridColor(new java.awt.Color(255, 255, 255));
        orphanageTb.getTableHeader().setReorderingAllowed(false);
        orphanageTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orphanageTbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(orphanageTb);
        if (orphanageTb.getColumnModel().getColumnCount() > 0) {
            orphanageTb.getColumnModel().getColumn(0).setResizable(false);
            orphanageTb.getColumnModel().getColumn(1).setResizable(false);
            orphanageTb.getColumnModel().getColumn(2).setResizable(false);
            orphanageTb.getColumnModel().getColumn(3).setResizable(false);
            orphanageTb.getColumnModel().getColumn(4).setResizable(false);
            orphanageTb.getColumnModel().getColumn(5).setResizable(false);
            orphanageTb.getColumnModel().getColumn(6).setResizable(false);
            orphanageTb.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new Color(0,0,0,(int)0.01), 3, true));

        idTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        idTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("ID");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Last Name");

        ageTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ageTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("First Name");

        weightTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        weightTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("Age");

        lastNameTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lastNameTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("Weight");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("Height");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setText("Gender");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setText("Blood Group");

        heightTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        heightTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bloodGroupCb.setBackground(new Color(0,0,0,(int)0.01));
        bloodGroupCb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bloodGroupCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        bloodGroupCb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        genderCb.setBackground(new Color(0,0,0,(int)0.01));
        genderCb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        genderCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        genderCb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        firstNameTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        firstNameTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        idErrLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        idErrLbl.setForeground(new java.awt.Color(255, 102, 102));

        firstNameErrLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        firstNameErrLbl.setForeground(new java.awt.Color(255, 102, 102));

        weightErrLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        weightErrLbl.setForeground(new java.awt.Color(255, 102, 102));

        ageErrLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ageErrLbl.setForeground(new java.awt.Color(255, 102, 102));

        lastNameErrLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lastNameErrLbl.setForeground(new java.awt.Color(255, 102, 102));

        genderErrLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        genderErrLbl.setForeground(new java.awt.Color(255, 102, 102));

        bloodGroupErrLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bloodGroupErrLbl.setForeground(new java.awt.Color(255, 102, 102));

        heightErrLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        heightErrLbl.setForeground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17)
                    .addComponent(jLabel15)
                    .addComponent(jLabel12))
                .addGap(63, 63, 63)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ageTf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                    .addComponent(firstNameTf, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastNameTf, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idTf, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(weightTf, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(60, 60, 60))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstNameErrLbl)
                                    .addComponent(lastNameErrLbl)
                                    .addComponent(ageErrLbl)
                                    .addComponent(weightErrLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(bloodGroupCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(genderCb, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(heightTf, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(heightErrLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel16)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(deleteBtn)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(genderErrLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(updateBtn)
                                        .addComponent(bloodGroupErrLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(idErrLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(idTf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16))
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idErrLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstNameErrLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addComponent(lastNameErrLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(heightTf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(heightErrLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderCb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(genderErrLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(bloodGroupCb, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bloodGroupErrLbl)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateBtn)
                            .addComponent(deleteBtn))
                        .addContainerGap(116, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(ageTf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ageErrLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(weightTf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(weightErrLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        searchBarCb.setBackground(new Color(0,0,0,(int)0.01));
        searchBarCb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        searchBarCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "First Name", "Last Name", "Age", "Weight", "Height", "Gender", "Blood Group" }));
        searchBarCb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel25.setText("Search By:");

        searchKeyTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        searchKeyTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        searchBtn.setText("Search Button");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        isDescending.setText("Descending Order");

        javax.swing.GroupLayout managePnlLayout = new javax.swing.GroupLayout(managePnl);
        managePnl.setLayout(managePnlLayout);
        managePnlLayout.setHorizontalGroup(
            managePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managePnlLayout.createSequentialGroup()
                .addGroup(managePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(managePnlLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, managePnlLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(managePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(managePnlLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(managePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(managePnlLayout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchBarCb, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(searchKeyTf, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(managePnlLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(searchBtn))
                    .addGroup(managePnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(isDescending)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        managePnlLayout.setVerticalGroup(
            managePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managePnlLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(managePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(managePnlLayout.createSequentialGroup()
                        .addComponent(isDescending)
                        .addGap(51, 51, 51)
                        .addGroup(managePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchBarCb, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchKeyTf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(searchBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage", managePnl);

        addPnl.setBackground(new java.awt.Color(236, 239, 239));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("First Name");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Last Name");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Weight");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Height");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Gender");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Blood Group");

        newFirstNameTf.setBackground(new Color(0,0,0,(int) 0.01*255));
        newFirstNameTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        newFirstNameTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        newLastNameTf.setBackground(new Color(0,0,0,(int) 0.01*255));
        newLastNameTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        newLastNameTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        newAgeTf.setBackground(new Color(0,0,0,(int) 0.01*255));
        newAgeTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        newAgeTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        newHeightTf.setBackground(new Color(0,0,0,(int) 0.01*255));
        newHeightTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        newHeightTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        newWeightTf.setBackground(new Color(0,0,0,(int) 0.01*255));
        newWeightTf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        newWeightTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Age");

        newGenderCb.setBackground(new Color(0,0,0,(int)0.01));
        newGenderCb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        newGenderCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        newGenderCb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        newBloodGroupCb.setBackground(new Color(0,0,0,(int)0.01));
        newBloodGroupCb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        newBloodGroupCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        newBloodGroupCb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        addFirstNameErrLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addFirstNameErrLbl.setForeground(new java.awt.Color(255, 153, 153));

        addGenderErrLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addGenderErrLbl.setForeground(new java.awt.Color(255, 153, 153));
        addGenderErrLbl.setToolTipText("");

        addBloodGroupErrLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addBloodGroupErrLbl.setForeground(new java.awt.Color(255, 153, 153));

        addLastNameErrLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addLastNameErrLbl.setForeground(new java.awt.Color(255, 153, 153));

        addAgeErrLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addAgeErrLbl.setForeground(new java.awt.Color(255, 153, 153));

        addWeightErrLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addWeightErrLbl.setForeground(new java.awt.Color(255, 153, 153));

        addHeightErrLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addHeightErrLbl.setForeground(new java.awt.Color(255, 153, 153));

        addBtn.setText("Add Child");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newGenderCb, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addLastNameErrLbl)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(addFirstNameErrLbl))
                                        .addComponent(newFirstNameTf, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                                        .addComponent(newLastNameTf)
                                        .addComponent(newAgeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(addAgeErrLbl)
                                    .addComponent(newWeightTf, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addWeightErrLbl)
                                    .addComponent(newHeightTf, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addHeightErrLbl)
                                    .addComponent(addGenderErrLbl)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addBloodGroupErrLbl)
                                    .addComponent(newBloodGroupCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(addBtn)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(newFirstNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addFirstNameErrLbl)
                .addGap(8, 8, 8)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newLastNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addLastNameErrLbl)
                .addGap(17, 17, 17)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(newAgeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addAgeErrLbl)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newWeightTf, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addWeightErrLbl)
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(newHeightTf, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addHeightErrLbl)
                .addGap(17, 17, 17)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(newGenderCb, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addGenderErrLbl)
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(newBloodGroupCb, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addBloodGroupErrLbl)))
                .addGap(22, 22, 22)
                .addComponent(addBtn)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout addPnlLayout = new javax.swing.GroupLayout(addPnl);
        addPnl.setLayout(addPnlLayout);
        addPnlLayout.setHorizontalGroup(
            addPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPnlLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(706, Short.MAX_VALUE))
        );
        addPnlLayout.setVerticalGroup(
            addPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPnlLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add ", addPnl);

        javax.swing.GroupLayout orphanageListPnlLayout = new javax.swing.GroupLayout(orphanageListPnl);
        orphanageListPnl.setLayout(orphanageListPnlLayout);
        orphanageListPnlLayout.setHorizontalGroup(
            orphanageListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        orphanageListPnlLayout.setVerticalGroup(
            orphanageListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane2.addTab("Orphanage List", orphanageListPnl);

        aboutUsPnl.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel20.setText("About Us");
        jLabel20.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel21.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(56, 111, 164));
        jLabel21.setText(" who have lost their home, offering a haven where children can find a family, even when they have none.");

        jLabel22.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(56, 111, 164));
        jLabel22.setText("An orphanage is a place where love is given to those");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel23.setText("Who We Are");
        jLabel23.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel35.setText("At HereToHelp, we are a compassionate family dedicated to providing a safe and loving home for children ");

        jLabel36.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel36.setText(" they need to build a brighter future. Through compassion and dedication, we ensure that no child is left behind.");

        jLabel37.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel37.setText("in need. Our mission is to nurture and empower every child, offering them the care, education and support ");

        javax.swing.GroupLayout aboutUsPnlLayout = new javax.swing.GroupLayout(aboutUsPnl);
        aboutUsPnl.setLayout(aboutUsPnlLayout);
        aboutUsPnlLayout.setHorizontalGroup(
            aboutUsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutUsPnlLayout.createSequentialGroup()
                .addGroup(aboutUsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutUsPnlLayout.createSequentialGroup()
                        .addGap(565, 565, 565)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(aboutUsPnlLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 1216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 95, Short.MAX_VALUE))
            .addGroup(aboutUsPnlLayout.createSequentialGroup()
                .addGroup(aboutUsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutUsPnlLayout.createSequentialGroup()
                        .addGap(574, 574, 574)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(aboutUsPnlLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addGroup(aboutUsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(aboutUsPnlLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(208, 208, 208))
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(aboutUsPnlLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(aboutUsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 1239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        aboutUsPnlLayout.setVerticalGroup(
            aboutUsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutUsPnlLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addGap(41, 41, 41)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("About us", aboutUsPnl);

        mainPnl.add(jTabbedPane2, java.awt.BorderLayout.CENTER);

        loginPnl.setMaximumSize(new java.awt.Dimension(640, 471));
        loginPnl.setMinimumSize(new java.awt.Dimension(640, 471));
        loginPnl.setPreferredSize(new java.awt.Dimension(640, 471));
        loginPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameTf.setBackground(new Color(0,0,0,(int)0.01));
        usernameTf.setForeground(new java.awt.Color(255, 255, 255));
        usernameTf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameTf.setText("Username");
        usernameTf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        usernameTf.setCaretColor(new java.awt.Color(255, 255, 255));
        usernameTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameTfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameTfFocusLost(evt);
            }
        });
        loginPnl.add(usernameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 200, 50));

        passwordTf.setBackground(new Color(0,0,0,0));
        passwordTf.setForeground(new java.awt.Color(255, 255, 255));
        passwordTf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordTf.setText("Password");
        passwordTf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        passwordTf.setCaretColor(new java.awt.Color(255, 255, 255));
        passwordTf.setEchoChar((char) 0);
        passwordTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordTfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordTfFocusLost(evt);
            }
        });
        loginPnl.add(passwordTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 200, 50));

        userIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/orphanage/resources/user.png"))); // NOI18N
        loginPnl.add(userIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("LOGIN");
        loginBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        loginBtn.setContentAreaFilled(false);
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        loginPnl.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 140, 30));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" System");
        loginPnl.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 80, 40));

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Welcome To Orphanage Management ");
        loginPnl.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 330, 70));

        lockIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/orphanage/resources/lock.png"))); // NOI18N
        loginPnl.add(lockIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/orphanage/resources/background.png"))); // NOI18N
        BackgroundImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        loginPnl.add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 380, 490));

        loginSideImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/orphanage/resources/loginImage.jpg"))); // NOI18N
        loginSideImageLabel.setText("jLabel25");
        loginPnl.add(loginSideImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, -10, 290, 480));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loadingPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        progressBar.setForeground(new Color(0,0,0));
        progressBar.setValue(50);
        progressBar.setBorder(null);
        progressBar.setBorderPainted(false);
        progressBar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        progressBar.setFocusable(false);
        progressBar.setRequestFocusEnabled(false);
        loadingPnl.add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 560, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/orphanage/resources/loadingbg.jpg"))); // NOI18N
        loadingPnl.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(loadingPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(loadingPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTfFocusGained
        if (getTfText(usernameTf).equals("Username")) {
            clearText(usernameTf);
        }
    }//GEN-LAST:event_usernameTfFocusGained

    private void passwordTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTfFocusGained
        if (getTfText(passwordTf).equals("Password")) {
            passwordTf.setEchoChar('*');
            clearText(passwordTf);
        }
    }//GEN-LAST:event_passwordTfFocusGained

    private void usernameTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTfFocusLost
        if (getTfText(usernameTf).equals("")) {
            setTfText(usernameTf, "Username");
        }
    }//GEN-LAST:event_usernameTfFocusLost

    private void passwordTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTfFocusLost
        if (getTfText(passwordTf).equals("")) {
            passwordTf.setEchoChar((char) 0);
            setTfText(passwordTf, "Password");
        }
    }//GEN-LAST:event_passwordTfFocusLost

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        if (isValidCredentials(getTfText(usernameTf), getTfText(passwordTf))) {
            loadScreen("MainScreen");
            setFullScreen();
            setLocationRelativeTo(null);
        } else {
            JOptionPane.showMessageDialog(null, "Username or Password is incorrect", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void orphanageTbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orphanageTbMouseClicked
        int row = orphanageTb.rowAtPoint(evt.getPoint());
        setTfText(idTf, String.valueOf(orphanageTb.getValueAt(row, 0)));
        setTfText(firstNameTf, (String) orphanageTb.getValueAt(row, 1));
        setTfText(lastNameTf, (String) orphanageTb.getValueAt(row, 2));
        setTfText(ageTf, String.valueOf(orphanageTb.getValueAt(row, 3)));
        setTfText(weightTf, String.valueOf(orphanageTb.getValueAt(row, 4)));
        setTfText(heightTf, String.valueOf(orphanageTb.getValueAt(row, 5)));
        genderCb.setSelectedItem(orphanageTb.getValueAt(row, 6));
        bloodGroupCb.setSelectedItem(orphanageTb.getValueAt(row, 7));

    }//GEN-LAST:event_orphanageTbMouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        try {
            boolean isValid = true;
            isValid &= validateField(idErrLbl, "Id is invalid", ValidationUtil.isValidId(Short.parseShort(getTfText(idTf))));
            isValid &= validateField(firstNameErrLbl, "First name is invalid", ValidationUtil.isValidName(getTfText(firstNameTf)));
            isValid &= validateField(lastNameErrLbl, "Last name is invalid", ValidationUtil.isValidName(getTfText(lastNameTf)));
            isValid &= validateField(ageErrLbl, "Age is invalid", ValidationUtil.isValidAge(Short.parseShort(getTfText(ageTf))));
            isValid &= validateField(weightErrLbl, "Weight is invalid", ValidationUtil.isValidWeight(Short.parseShort(getTfText(weightTf))));
            isValid &= validateField(heightErrLbl, "Height is invalid", ValidationUtil.isValidHeight(Short.parseShort(getTfText(heightTf))));
            isValid &= validateField(genderErrLbl, "Gender is invalid", ValidationUtil.isValidGender(genderCb.getSelectedItem().toString()));
            isValid &= validateField(bloodGroupErrLbl, "Blood Group is invalid", ValidationUtil.isValidBloodGroup(bloodGroupCb.getSelectedItem().toString()));
            if (isValid) {
                short id = Short.parseShort(getTfText(idTf));
                String firstName = getTfText(firstNameTf);
                String lastName = getTfText(lastNameTf);
                short age = Short.parseShort(getTfText(ageTf));
                short weight = Short.parseShort(getTfText(weightTf));
                short height = Short.parseShort(getTfText(heightTf));
                String gender = (String) genderCb.getSelectedItem();
                String bloodGroup = (String) bloodGroupCb.getSelectedItem();

                OrphanModel newOrphan = new OrphanModel(id, firstName, lastName, age, weight, height, gender, bloodGroup);
                orphanList.put((int) id, newOrphan);
                JOptionPane.showMessageDialog(null, "Orphan has been updated", "update Succesful", JOptionPane.INFORMATION_MESSAGE);
                refreshTable();
            }
        } catch (NumberFormatException E) {
            JOptionPane.showMessageDialog(null, "Invalid Details", "update Unsuccesful", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private boolean validateField(JLabel label, String msg, boolean isValidFormat) {
        if (!isValidFormat) {
            label.setText(msg);
            return false;
        } else {
            label.setText("");
            return true;
        }
    }
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        try {
            boolean isValid = true;
            isValid &= validateField(addFirstNameErrLbl, "First name is invalid", ValidationUtil.isValidName(getTfText(newFirstNameTf)));
            isValid &= validateField(addLastNameErrLbl, "Last name is invalid", ValidationUtil.isValidName(getTfText(newLastNameTf)));
            isValid &= validateField(addAgeErrLbl, "Age is invalid", ValidationUtil.isValidAge(Short.parseShort(getTfText(newAgeTf))));
            isValid &= validateField(addWeightErrLbl, "Weight is invalid", ValidationUtil.isValidWeight(Short.parseShort(getTfText(newWeightTf))));
            isValid &= validateField(addHeightErrLbl, "Height is invalid", ValidationUtil.isValidHeight(Short.parseShort(getTfText(newHeightTf))));
            isValid &= validateField(addGenderErrLbl, "Gender is invalid", ValidationUtil.isValidGender(newGenderCb.getSelectedItem().toString()));
            isValid &= validateField(addBloodGroupErrLbl, "Blood Group is invalid", ValidationUtil.isValidBloodGroup(newBloodGroupCb.getSelectedItem().toString()));

            if (isValid) {
                String firstName = getTfText(newFirstNameTf);
                String lastName = getTfText(newLastNameTf);
                short age = Short.parseShort(getTfText(newAgeTf));
                short weight = Short.parseShort(getTfText(newWeightTf));
                short height = Short.parseShort(getTfText(newHeightTf));
                String gender = newGenderCb.getSelectedItem().toString();
                String bloodGroup = newBloodGroupCb.getSelectedItem().toString();
                OrphanModel newOrphan = new OrphanModel(++OrphanageApp.id, firstName, lastName, age, weight, height, gender, bloodGroup);
                orphanList.put((int) OrphanageApp.id, newOrphan);
                JOptionPane.showMessageDialog(null, "Orphan has been added", "Insert Succesful", JOptionPane.INFORMATION_MESSAGE);
                refreshTable();
            }
        } catch (NumberFormatException E) {
            JOptionPane.showMessageDialog(null, "Invalid Details", "Insert Unsuccesful", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Do you want to proceed?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (response == 0) {
            try {
                int idToBeDeleted = Integer.parseInt(getTfText(idTf));
                orphanList.remove(idToBeDeleted);
                refreshTable();
                JOptionPane.showMessageDialog(null, "Orphan Detail has been deleletd", "Delete Succesful", JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException E) {
                JOptionPane.showMessageDialog(null, "Invalid Details", "Delete Unsuccesful", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed

        String searchBy = (String) searchBarCb.getSelectedItem();
        String target = getTfText(searchKeyTf);
        searchByAttribute(searchBy, target);

    }//GEN-LAST:event_searchBtnActionPerformed

    private void searchByAttribute(String searchBy, String target) {
        ArrayList<OrphanModel> list = new ArrayList<>(orphanList.values());
        try {
            switch (searchBy) {
                case "Id" -> {
                    refreshTable(BinarySearch.binarySearchbyId(SelectionSort.sortById(list, false), 0, list.size() - 1, Short.parseShort(target)));
                }
                case "First Name" -> {
                    refreshTable(BinarySearch.binarySearchbyFirstName(MergeSort.mergeSort(list, false, "FirstName"), 0, list.size() - 1, target));
                }
                case "Last Name" -> {
                    refreshTable(BinarySearch.binarySearchbyLastName(InsertionSort.sortByLastName(list, false), 0, list.size() - 1, target));
                }
                case "Age" -> {
                    refreshTable(BinarySearch.binarySearchbyAge(InsertionSort.sortByAge(list, false), 0, list.size() - 1, Short.parseShort(target)));
                }
                case "Weight" -> {
                    refreshTable(BinarySearch.binarySearchbyWeight(MergeSort.mergeSort(list, false, "Weight"), 0, list.size() - 1, Short.parseShort(target)));
                }
                case "Height" -> {
                    refreshTable(BinarySearch.binarySearchbyHeight(MergeSort.mergeSort(list, false, "Height"), 0, list.size() - 1, Short.parseShort(target)));
                }
                case "Gender" -> {
                    refreshTable(BinarySearch.binarySearchbyGender(SelectionSort.sortByGender(list, false), 0, list.size() - 1, target));
                }
                case "Blood Group" -> {
                    refreshTable(BinarySearch.binarySearchbyBloodGroup(SelectionSort.sortByBloodGroup(list, false), 0, list.size() - 1, target));
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "InValid Data Found", "Search Unsuccesful", JOptionPane.ERROR_MESSAGE);
        } catch (NoSuchElementException e) {
            JOptionPane.showMessageDialog(null, "No Data Found", "Search Unsuccesful", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrphanageApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrphanageApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrphanageApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrphanageApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        OrphanageApp app = new OrphanageApp();
        //</editor-fold>

        /* Create and display the form */
 /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            app.setVisible(true);
        });

        app.startProgress();
    }

    private void setFullScreen() {
        // Maximize the frame 
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    private void initializeLayout() {
        cardLayout = new java.awt.CardLayout();
        getContentPane().setLayout(cardLayout);

        // Add panels with unique identifiers
        getContentPane().add(loadingPnl, "LoadingScreen");
        getContentPane().add(loginPnl, "LoginScreen");
        getContentPane().add(mainPnl, "MainScreen");

        // Start with the loading screen
        loadScreen("LoadingScreen");
    }

    private void loadScreen(String screenName) {
        cardLayout.show(getContentPane(), screenName);
    }

    private void startProgress() {
        javax.swing.SwingWorker<Void, Integer> worker = new javax.swing.SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {
                for (int i = 0; i <= 100; i++) {
                    Thread.sleep(30); // Simulated delay for progress bar
                    publish(i); // Publish progress
                }
                return null;
            }

            @Override
            protected void process(java.util.List<Integer> chunks) {
                int progress = chunks.get(chunks.size() - 1);
                progressBar.setValue(progress);
            }

            @Override
            protected void done() {
                loadScreen("LoginScreen"); // Switch to login screen

            }
        };
        worker.execute(); // Start the worker thread
    }

    private void refreshTable() {
        DefaultTableModel table = (DefaultTableModel) orphanageTb.getModel();

        // Clear existing rows if needed
        table.setRowCount(0);

        // Populate the table with student data
        this.orphanList.forEach((id, orphan) -> table.addRow(new Object[]{
            orphan.getOrphanID(),
            orphan.getFirstName(),
            orphan.getLastName(),
            orphan.getAge(),
            orphan.getWeight(),
            orphan.getHeight(),
            orphan.getGender(),
            orphan.getBloodGroup()
        }));

    }

    private void refreshTable(ArrayList<OrphanModel> list) {
        DefaultTableModel table = (DefaultTableModel) orphanageTb.getModel();

        // Clear existing rows if needed
        table.setRowCount(0);

        list.forEach(orphan -> table.addRow(new Object[]{
            orphan.getOrphanID(),
            orphan.getFirstName(),
            orphan.getLastName(),
            orphan.getAge(),
            orphan.getWeight(),
            orphan.getHeight(),
            orphan.getGender(),
            orphan.getBloodGroup()
        }));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JPanel aboutUsPnl;
    private javax.swing.JLabel addAgeErrLbl;
    private javax.swing.JLabel addBloodGroupErrLbl;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel addFirstNameErrLbl;
    private javax.swing.JLabel addGenderErrLbl;
    private javax.swing.JLabel addHeightErrLbl;
    private javax.swing.JLabel addLastNameErrLbl;
    private javax.swing.JPanel addPnl;
    private javax.swing.JLabel addWeightErrLbl;
    private javax.swing.JLabel ageErrLbl;
    private javax.swing.JTextField ageTf;
    private javax.swing.JComboBox<String> bloodGroupCb;
    private javax.swing.JLabel bloodGroupErrLbl;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel firstNameErrLbl;
    private javax.swing.JTextField firstNameTf;
    private javax.swing.JComboBox<String> genderCb;
    private javax.swing.JLabel genderErrLbl;
    private javax.swing.JLabel heightErrLbl;
    private javax.swing.JTextField heightTf;
    private javax.swing.JPanel homePagePnl;
    private javax.swing.JLabel idErrLbl;
    private javax.swing.JTextField idTf;
    private javax.swing.JCheckBox isDescending;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lastNameErrLbl;
    private javax.swing.JTextField lastNameTf;
    private javax.swing.JPanel loadingPnl;
    private javax.swing.JLabel lockIconLabel;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel loginPnl;
    private javax.swing.JLabel loginSideImageLabel;
    private javax.swing.JPanel mainPnl;
    private javax.swing.JPanel managePnl;
    private javax.swing.JTextField newAgeTf;
    private javax.swing.JComboBox<String> newBloodGroupCb;
    private javax.swing.JTextField newFirstNameTf;
    private javax.swing.JComboBox<String> newGenderCb;
    private javax.swing.JTextField newHeightTf;
    private javax.swing.JTextField newLastNameTf;
    private javax.swing.JTextField newWeightTf;
    private javax.swing.JPanel orphanageListPnl;
    private javax.swing.JTable orphanageTb;
    private javax.swing.JPasswordField passwordTf;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JComboBox<String> searchBarCb;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchKeyTf;
    private javax.swing.JButton updateBtn;
    private javax.swing.JLabel userIconLabel;
    private javax.swing.JTextField usernameTf;
    private javax.swing.JLabel weightErrLbl;
    private javax.swing.JTextField weightTf;
    // End of variables declaration//GEN-END:variables

}
